# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
use_bioc: true
bioc_required: true
warnings_are_errors: true

r:
  - release
  - devel

r_check_args: --as-cran

notifications:
  email:
    on_success: change
    on_failure: change

  after_success:
    - Rscript -e 'covr::coveralls(type = "all")'